MovieTitles/MovieTitles/Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieTitles.Models;

namespace MovieTitles.Controllers
{   
    public class TitlesController : Controller
    {
        private TitlesContext db = new TitlesContext();


        /// <summary>
        /// SearchTitles
        /// </summary>
        /// <param name="movieGenre"></param>
        /// <param name="searchString"></param>
        /// <returns>Action Results</returns>
        public ActionResult Index(string movieGenre, string searchString)
        {
            // Keep a seperate list of Genres
            var GenreLst = new List<string>();

            var GenreQry = from g in db.Genres
                           orderby g.Name
                           select g.Name;


            GenreLst.AddRange(GenreQry.Distinct());
            ViewData["movieGenre"] = new SelectList(GenreLst);

            var titles = (from t in db.Titles
                          orderby t.TitleName
                          select t).Distinct();


            // Search for our titles based on a input string
            if (!String.IsNullOrEmpty(searchString))
            {
                titles = titles.Where(ta => ta.TitleName.Contains(searchString));
            }

            // If Genres are not being search return the default list of titles
            if (string.IsNullOrEmpty(movieGenre))
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    return View(titles);
                }

                else
                {   //                 
                    return View(titles);
                }

            }
            else
            {   // Get the list by Genres if necessary
                var genres = (from t in db.Titles
                              join tg in db.TitleGenres on t.TitleId equals tg.TitleId
                              join gr in db.Genres on tg.GenreId equals gr.Id
                              where gr.Name == movieGenre
                              orderby t.TitleName
                              select t).Distinct();


                return View(genres);
            }

        }

        /// <summary>
        /// Details
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult</returns>
        public ActionResult Details(int id = 0)
        {
            Title title = db.Titles.Single(t => t.TitleId == id);
            if (title == null)
            {
                return HttpNotFound();
            }
            return View(title);
        }
        
        /// <summary>
        /// Dispose of all unnecessary resources by Default
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MovieTitles/MovieTitles/Views/Titles/Create.cshtml
@model MovieTitles.Models.Title

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Title</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleName)
            @Html.ValidationMessageFor(model => model.TitleName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleNameSortable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleNameSortable)
            @Html.ValidationMessageFor(model => model.TitleNameSortable)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleTypeId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleTypeId)
            @Html.ValidationMessageFor(model => model.TitleTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseYear)
            @Html.ValidationMessageFor(model => model.ReleaseYear)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProcessedDateTimeUTC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProcessedDateTimeUTC)
            @Html.ValidationMessageFor(model => model.ProcessedDateTimeUTC)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MovieTitles/MovieTitles/Views/Titles/Delete.cshtml
@model MovieTitles.Models.Title

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Title</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleNameSortable)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleNameSortable)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleTypeId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleTypeId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseYear)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseYear)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProcessedDateTimeUTC)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProcessedDateTimeUTC)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MovieTitles/MovieTitles/Views/Titles/Details.cshtml
@model MovieTitles.Models.Title

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Title</legend>
    
    <div class="display-container">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleName):
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleName)
    </div>
    </div>
       
    <div class="display-container">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseYear):
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseYear)
    </div>
    </div>
    
    <div class="display-container">
    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProcessedDateTimeUTC):
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProcessedDateTimeUTC)
    </div>
    </div>
</fieldset>
<p>    
    @Html.ActionLink("Back to List", "Index")
</p>

MovieTitles/MovieTitles/Views/Titles/Edit.cshtml
@model MovieTitles.Models.Title

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Title</legend>

        @Html.HiddenFor(model => model.TitleId)

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleName)
            @Html.ValidationMessageFor(model => model.TitleName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleNameSortable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleNameSortable)
            @Html.ValidationMessageFor(model => model.TitleNameSortable)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TitleTypeId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TitleTypeId)
            @Html.ValidationMessageFor(model => model.TitleTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseYear)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseYear)
            @Html.ValidationMessageFor(model => model.ReleaseYear)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProcessedDateTimeUTC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProcessedDateTimeUTC)
            @Html.ValidationMessageFor(model => model.ProcessedDateTimeUTC)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MovieTitles/MovieTitles/Views/Titles/Index.cshtml
@model IEnumerable<MovieTitles.Models.Title>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p> 
    @using (Html.BeginForm("Index","Titles",FormMethod.Get)){     
         <p>Genre: @Html.DropDownList("movieGenre", "All")   
           Title: @Html.TextBox("SearchString")   
         <input type="submit" value="Search" />
         </p> 
        } 
</p>
<table cellpadding="3" cellspacing="3" style="width:70%;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleName)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProcessedDateTimeUTC)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TitleName)
        </td>       
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProcessedDateTimeUTC)
        </td>
        <td>            
            @Html.ActionLink("Details", "Details", new { id=item.TitleId }) 
        </td>
    </tr>
}

</table>